import "server-only";

import {
  createCipheriv,
  createDecipheriv,
  createHash,
  randomBytes,
  timingSafeEqual,
} from "node:crypto";
import { Secret, TOTP } from "otpauth";
import type { Role } from "@prisma/client";
import { prisma } from "@/server/db/client";

// SECURITY_ARCHITECTURE.md §4.2 / BACKEND_ARCHITECTURE.md §16.3: MFA is
// mandatory for these roles — cross-branch blast radius is the deciding
// factor. branch_manager is deliberately excluded (single-branch exposure);
// see §16.3 for the full rationale and the note that this bar SHOULD be
// lowered where a single branch's exposure is itself significant.
export const MFA_REQUIRED_ROLES = new Set<Role>(["ADMIN", "FINANCE", "OPS_MANAGER"]);

export function staffRoleRequiresMfa(role: Role): boolean {
  return MFA_REQUIRED_ROLES.has(role);
}

// ---------------------------------------------------------------------------
// User.totpSecret encryption at rest (SECURITY_ARCHITECTURE.md §16.2:
// MFA_ENCRYPTION_KEY is independent from AUTH_SECRET so rotating one never
// invalidates the other). AES-256-GCM via Node's built-in crypto — no extra
// dependency needed for this half of the problem.
//
// MFA_ENCRYPTION_KEY must be a base64-encoded 32-byte key, e.g. generated
// with `openssl rand -base64 32`.
// ---------------------------------------------------------------------------

const GCM_IV_LENGTH = 12;

function getEncryptionKey(): Buffer {
  const raw = process.env.MFA_ENCRYPTION_KEY;
  if (!raw) {
    throw new Error(
      "MFA_ENCRYPTION_KEY is not set — required to encrypt/decrypt TOTP secrets."
    );
  }
  const key = Buffer.from(raw, "base64");
  if (key.length !== 32) {
    throw new Error(
      "MFA_ENCRYPTION_KEY must decode to exactly 32 bytes (base64-encoded)."
    );
  }
  return key;
}

export function encryptTotpSecret(plainBase32: string): string {
  const key = getEncryptionKey();
  const iv = randomBytes(GCM_IV_LENGTH);
  const cipher = createCipheriv("aes-256-gcm", key, iv);
  const ciphertext = Buffer.concat([
    cipher.update(plainBase32, "utf8"),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();
  return [iv, authTag, ciphertext].map((b) => b.toString("base64")).join(":");
}

export function decryptTotpSecret(encrypted: string): string {
  const [ivB64, authTagB64, ciphertextB64] = encrypted.split(":");
  if (!ivB64 || !authTagB64 || !ciphertextB64) {
    throw new Error("Malformed encrypted TOTP secret.");
  }
  const key = getEncryptionKey();
  const decipher = createDecipheriv(
    "aes-256-gcm",
    key,
    Buffer.from(ivB64, "base64")
  );
  decipher.setAuthTag(Buffer.from(authTagB64, "base64"));
  return Buffer.concat([
    decipher.update(Buffer.from(ciphertextB64, "base64")),
    decipher.final(),
  ]).toString("utf8");
}

// ---------------------------------------------------------------------------
// TOTP enrollment/verification (RFC 6238) — SECURITY_ARCHITECTURE.md §4.2:
// TOTP only, no SMS. 6 digits, 30s period, SHA1 (the near-universal default
// every authenticator app — Google Authenticator, Authy, 1Password —
// assumes; a non-default algorithm/digit count breaks compatibility with
// apps that don't read those fields from the provisioning URI).
// ---------------------------------------------------------------------------

export function generateTotpSecret(): string {
  return new Secret({ size: 20 }).base32;
}

export function buildTotpProvisioningUri(email: string, secretBase32: string): string {
  const totp = new TOTP({
    issuer: "Morel",
    label: email,
    secret: Secret.fromBase32(secretBase32),
    algorithm: "SHA1",
    digits: 6,
    period: 30,
  });
  return totp.toString();
}

export function verifyTotpToken(secretBase32: string, token: string): boolean {
  if (!/^\d{6}$/.test(token)) return false;
  const delta = TOTP.validate({
    token,
    secret: Secret.fromBase32(secretBase32),
    algorithm: "SHA1",
    digits: 6,
    period: 30,
    window: 1,
  });
  return delta !== null;
}

// ---------------------------------------------------------------------------
// Recovery codes (SECURITY_ARCHITECTURE.md §4.2: "stored hashed,
// single-use"). SHA-256, not argon2 — these are 40-bit-entropy random
// tokens generated by us, not user-chosen passwords, so there's no
// low-entropy guessing risk for a slow hash to defend against; argon2 here
// would only add real latency to every recovery-code login for no security
// benefit. Comparison still uses a constant-time check.
// ---------------------------------------------------------------------------

const RECOVERY_CODE_COUNT = 10;

function hashRecoveryCode(code: string): string {
  return createHash("sha256").update(code).digest("hex");
}

function formatRecoveryCode(): string {
  // 5 random bytes -> 10 hex chars, split for readability (e.g. "a1b2c-d3e4f").
  const hex = randomBytes(5).toString("hex");
  return `${hex.slice(0, 5)}-${hex.slice(5, 10)}`;
}

export function generateRecoveryCodes(): string[] {
  return Array.from({ length: RECOVERY_CODE_COUNT }, formatRecoveryCode);
}

/**
 * Verifies a recovery code against the user's unused codes and, if valid,
 * consumes it (marks it used) in the same call — single-use is enforced
 * here, not by the caller.
 */
export async function consumeRecoveryCode(
  userId: string,
  code: string
): Promise<boolean> {
  const normalized = code.trim().toLowerCase();
  if (!normalized) return false;
  const candidateHash = Buffer.from(hashRecoveryCode(normalized), "hex");

  const unused = await prisma.recoveryCode.findMany({
    where: { userId, usedAt: null },
    select: { id: true, codeHash: true },
  });

  const match = unused.find((row) => {
    const storedHash = Buffer.from(row.codeHash, "hex");
    return (
      storedHash.length === candidateHash.length &&
      timingSafeEqual(storedHash, candidateHash)
    );
  });
  if (!match) return false;

  // Fail closed: if this update somehow raced with another consumption of
  // the same row, updateMany's count tells us so — count === 0 means a
  // concurrent request already used it, and this one must not succeed too.
  const result = await prisma.recoveryCode.updateMany({
    where: { id: match.id, usedAt: null },
    data: { usedAt: new Date() },
  });
  return result.count === 1;
}

/** Generates and stores a fresh batch of recovery codes, replacing any
 * existing ones for the user (only ever called once, at MFA enrollment). */
export async function issueRecoveryCodes(userId: string): Promise<string[]> {
  const codes = generateRecoveryCodes();
  await prisma.$transaction([
    prisma.recoveryCode.deleteMany({ where: { userId } }),
    prisma.recoveryCode.createMany({
      data: codes.map((code) => ({
        userId,
        codeHash: hashRecoveryCode(code.trim().toLowerCase()),
      })),
    }),
  ]);
  return codes;
}
